#!/bin/zsh

# Restore Dock
defaults write com.apple.dock autohide -bool true && killall Dock
defaults delete com.apple.dock autohide-delay && killall Dock
defaults write com.apple.dock no-bouncing -bool FALSE && killall Dock

# Set Hot Corners
defaults write com.apple.dock wvous-tl-corner -int 4
defaults write com.apple.dock wvous-tr-corner -int 2
